-- M5 schema snapshot — pass_01
-- All tables at M5: SpecRun extended with specialist_crispe_prompt +
-- MetaPromptEvent node + META_PROMPT_ADDS rel + ANALYZED_META rel

-- M1 tables (unchanged)
CREATE NODE TABLE MilestoneRun (
  run_id STRING,
  milestone STRING,
  model STRING,
  timestamp STRING,
  PRIMARY KEY (run_id)
);

CREATE NODE TABLE FrameworkLayer (
  id STRING,
  name STRING,
  run_id STRING,
  dimension STRING,
  build_output STRING,
  file_path STRING,
  file_hash STRING,
  file_size_bytes INT64,
  build_time_ms DOUBLE,
  output_char_count INT64,
  output_token_est INT64,
  PRIMARY KEY (id)
);

CREATE REL TABLE CAPTURED_IN (FROM FrameworkLayer TO MilestoneRun);

-- SpecRun: M4 columns + M5 addition
-- specialist_crispe_prompt: the CRISPE meta-prompt generated from this output
--   '' for M0-M4 rows (CRISPE was not generated by prior milestones)
CREATE NODE TABLE SpecRun (
  id STRING,
  run_id STRING,
  milestone STRING,
  brief_label STRING,
  selected_lang STRING,
  layer STRING,
  confidence DOUBLE,
  justification_char_count INT64,
  latency_ms DOUBLE,
  model STRING,
  timestamp STRING,
  reasoning_step_count INT64,
  evaluation_depth STRING,
  revised BOOLEAN,
  revision_notes STRING,
  specialist_crispe_prompt STRING,
  PRIMARY KEY (id)
);

CREATE REL TABLE SPEC_CAPTURED_IN (FROM SpecRun TO MilestoneRun);

-- AnalysisNote: unchanged from M4
CREATE NODE TABLE AnalysisNote (
  id STRING,
  session STRING,
  by STRING,
  subject STRING,
  signal STRING,
  value STRING,
  note STRING,
  milestone STRING,
  hypothesis_id STRING,
  direction STRING,
  metric_before DOUBLE,
  metric_after DOUBLE,
  PRIMARY KEY (id)
);

CREATE REL TABLE ANALYZED (FROM AnalysisNote TO FrameworkLayer);
CREATE REL TABLE ANALYZED_RUN (FROM AnalysisNote TO MilestoneRun);
CREATE REL TABLE ANALYZED_SPEC (FROM AnalysisNote TO SpecRun);

-- M3 cross-schema edge (unchanged)
CREATE REL TABLE REASONING_ADDS (
  FROM SpecRun TO SpecRun,
  confidence_delta DOUBLE,
  step_count INT64,
  evaluation_depth STRING,
  adds_candidate_rejection BOOLEAN
);

-- M4 nodes/rels (unchanged)
CREATE NODE TABLE RevisionEvent (
  id STRING,
  run_id STRING,
  brief_label STRING,
  revised BOOLEAN,
  cai_principle_triggered STRING,
  assumption_inventory_added BOOLEAN,
  PRIMARY KEY (id)
);

CREATE REL TABLE VERIFICATION_ADDS (
  FROM SpecRun TO SpecRun,
  revised BOOLEAN,
  confidence_delta DOUBLE,
  cai_principle_triggered STRING,
  signal_count_below_threshold INT64,
  assumption_inventory_added BOOLEAN
);

-- M5 additions: CRISPE meta-prompt quality signals
CREATE NODE TABLE MetaPromptEvent (
  id STRING,
  run_id STRING,
  brief_label STRING,
  crispe_field_count INT64,
  capacity_char_count INT64,
  insight_char_count INT64,
  statement_char_count INT64,
  capacity_matches_lang BOOLEAN,
  PRIMARY KEY (id)
);

-- M5 cross-schema edge: M4 SpecRun → M5 SpecRun (all 3 briefs — first full coverage)
CREATE REL TABLE META_PROMPT_ADDS (
  FROM SpecRun TO SpecRun,
  crispe_field_count INT64,
  prompt_char_count INT64,
  capacity_matches_lang BOOLEAN
);

-- M5 analysis edge: AnalysisNote → MetaPromptEvent (for Claude-in-loop)
CREATE REL TABLE ANALYZED_META (FROM AnalysisNote TO MetaPromptEvent);
